exclude:
  - .build
opt_in_rules: [all]
analyzer_rules: [all]
disabled_rules:
  - anonymous_argument_in_multiline_closure
  - closure_body_length
  - conditional_returns_on_newline
  - cyclomatic_complexity
  - explicit_acl
  - explicit_top_level_acl
  - explicit_type_interface
  - force_unwrapping
  - indentation_width
  - missing_docs
  - multiline_parameters_brackets
  - no_extension_access_modifier
  - no_grouping_extension
  - no_magic_numbers
  - prefixed_toplevel_constant
  - required_deinit
  - sorted_imports
  - switch_case_on_newline
file_length:
  warning: 500
  error: 600
function_body_length:
  warning: 200
  error: 300
trailing_comma:
  mandatory_comma: true
