public enum XcodeScripting: String {
    case analyzerIssue = "analyzer issue"
    case application = "application"
    case buildConfiguration = "build configuration"
    case buildError = "build error"
    case buildSetting = "build setting"
    case buildWarning = "build warning"
    case device = "device"
    case document = "document"
    case fileDocument = "file document"
    case project = "project"
    case resolvedBuildSetting = "resolved build setting"
    case runDestination = "run destination"
    case schemeActionIssue = "scheme action issue"
    case schemeActionResult = "scheme action result"
    case scheme = "scheme"
    case sourceDocument = "source document"
    case target = "target"
    case testFailure = "test failure"
    case textDocument = "text document"
    case window = "window"
    case workspaceDocument = "workspace document"
}